### ISSUE TITLE
Small improvements Add order and adding short infos

### ISSUE THREAD

**Issue by senpl** [hovancik/later-on#11]
I think adding new Remainders should be first, not last on list(currently the longer list the more scroll required).
And during adding if notification title and body are empty it probably could be filled with name. Of course it could be optional , but this seems like expected bahaviour.

**Comment by hovancik** [comment]
Yeah, I am not that good with UI :) I wanted to add some sort of Modal for adding new Reminder but didn't put much thought into it. 

What do you mean with the body and title? You mean when showing notification or as "default value" and thus saved as such when creating it in "DB"? 

I need to look whether name is really needed at all...

**Comment by senpl** [comment]
> What do you mean with the body and title?

Notification title and body. And yes, if you get rid of name than just notification title will be enough.

**Comment by hovancik** [comment]
I've removed name.

**Comment by hovancik** [comment]
I've released 0.0.4 with changes
